### ISSUE TITLE
Trigger validation using ajax post

### ISSUE THREAD

**Issue by dheoxic** [NonFactors/Wellidate#1]
First of all, great plugin.
Validations work perfectly upon submitting the form using `<input type="submit"/>`. 
In case i want to validate the form using an ajax post, how am i gonna do it?
I post data from my form using the code below:
`var data = $('form').serialize();`
`$.ajax({`
`      type: 'post', data: data, url: 'urltopost', `
`      success: function(e){  //do something     }`
`})`
My gratitude in advance.

**Comment by Muchiachio** [comment]
Depends what you are trying todo, there are few methods
```JS
var wellidate = new Wellidate($('form')[0]);
wellidate.form(); // Validates the form and shows the errors to the user.
wellidate.isValid(); // Validates the form without showing them to the user.
wellidate.validate(); // Validates the form and returns the validation results for each element.
```
There are example usages on the [API](https://nonfactors.github.io/Wellidate/api) page.

**Comment by dheoxic** [comment]
Got it. Thanks.
