### ISSUE TITLE
Date Format Issue?Limitation?

### ISSUE THREAD

**Issue by dheoxic** [NonFactors/Wellidate#2]
The validator reads this date format `8/1/2019 3:10:20 PM` as invalid. I don't know if this is an issue with the plugin or I am just missing something.

**Comment by Muchiachio** [comment]
By default `date` validator validates ISO date and not date + time. You will have to register your own datetime validator or override date validator to validate dates in your locale. For example using moment
```JS
Wellidate.prototype.rules.date.isValid = function () {
    return !this.element.value || moment(this.element.value).isValid();
};
```

**Comment by dheoxic** [comment]
Ohh i see. This is what i did before seeing your suggestion.
`Wellidate.prototype.default.rules.isValid = function () {`
`return !this.element.value || moment(this.element.value).isValid();`
`};`
Also ended up getting a deprecation warning from moment.js but fixed it by correcting my date format from `mm/dd/yyyy HH:mm:ssZ` to `mm/dd/yyyy THH:mm:ssZ`

Thank you.
