### ISSUE TITLE
Issue on radio buttons with the same name

### ISSUE THREAD

**Issue by dheoxic** [NonFactors/Wellidate#4]
I'm getting the error below when i have more than 1 radio buttons with the same name inside a form. This happens when I put periods on radio button names like
```<input type='radio' name='some.radioname' id='some_radioname'/>```

![image](https://user-images.githubusercontent.com/50933655/75856313-08a92c80-5e2f-11ea-9bd2-3067e4225a62.png)

**Comment by Muchiachio** [comment]
Which validation are you applying on the input?

**Comment by dheoxic** [comment]
I am not applying any validation on the radio buttons. The error shows when performing `frm.validate()`, `frm.form()`, or `frm.isValid()`

**Comment by Muchiachio** [comment]
Strange, I can't repro with
```html
<form>
    <input type="radio" name="some.radioname" />
    <input type="radio" name="some.radioname" />
    <input type="radio" name="some.radioname" />
    <button>Submit</button>
</form>
```
In theory this shouldn't even validate anything and it doesn't for me locally, because there are no rules applied.

**Comment by dheoxic** [comment]
Thank you for the response. Might have something to do with how I render my controls.

**Comment by Muchiachio** [comment]
Managed to repro when it's validated, will see why it happens and fix.
